#!/usr/bin/env bash
# Configure k3s containerd and the NVIDIA device plugin for bare-metal GPU workloads
# cspell:ignore dropin
set -o errexit -o nounset

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$SCRIPT_DIR/../.." && pwd))"
# shellcheck source=../../scripts/lib/common.sh
source "$REPO_ROOT/scripts/lib/common.sh"

# Pinned NVIDIA Kubernetes device plugin. Bare metal exposes a working NVML, so
# the official plugin replaces the generic device plugin the WSL path needs.
DEVICE_PLUGIN_VERSION="${DEVICE_PLUGIN_VERSION:-v0.17.4}"

show_help() {
  cat << EOF
Usage: $(basename "$0") [OPTIONS]

Point k3s containerd at the NVIDIA container runtime and install the NVIDIA
Kubernetes device plugin so pods can request nvidia.com/gpu.

The NVIDIA runtime is made the containerd default rather than an opt-in
RuntimeClass because the offload spec has no runtimeClassName field, so
generated server Deployments cannot select a runtime handler themselves.

OPTIONS:
    -h, --help               Show this help message
    -c, --context NAME       Kubeconfig context (default: $DEFAULT_CONTEXT)
    --plugin-version VER     Device plugin version (default: $DEVICE_PLUGIN_VERSION)
    --config-preview         Print configuration and exit

EXAMPLES:
    $(basename "$0")
    $(basename "$0") --context gpu-offload-k3s
EOF
}

# Defaults
DEFAULT_CONTEXT="gpu-offload-k3s"
context="$DEFAULT_CONTEXT"
config_preview=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)          show_help; exit 0 ;;
    -c|--context)       context="$2"; shift 2 ;;
    --plugin-version)   DEVICE_PLUGIN_VERSION="$2"; shift 2 ;;
    --config-preview)   config_preview=true; shift ;;
    *)                  fatal "Unknown option: $1" ;;
  esac
done

require_tools kubectl nvidia-smi

#------------------------------------------------------------------------------
# Gather Configuration
#------------------------------------------------------------------------------

containerd_dir=/var/lib/rancher/k3s/agent/etc/containerd
generated_config="$containerd_dir/config.toml"
k3s_dropin_dir=/etc/rancher/k3s/config.yaml.d
k3s_dropin="$k3s_dropin_dir/10-nvidia-default-runtime.yaml"
register_timeout="${GPU_PLUGIN_REGISTER_TIMEOUT:-600}"

if [[ "$config_preview" == "true" ]]; then
  section "Configuration Preview"
  print_kv "Kube context" "$context"
  print_kv "Device plugin" "$DEVICE_PLUGIN_VERSION"
  print_kv "k3s drop-in" "$k3s_dropin"
  exit 0
fi

command -v nvidia-container-runtime > /dev/null 2>&1 \
  || fatal "nvidia-container-runtime not found; run the NVIDIA Container Toolkit task first"

#------------------------------------------------------------------------------
# Configure Containerd
#------------------------------------------------------------------------------
section "Configuring the Default Container Runtime"

sudo test -f "$generated_config" || fatal "k3s containerd config not found at $generated_config"

sudo grep -q 'nvidia-container-runtime' "$generated_config" \
  || fatal "k3s did not auto-detect the NVIDIA runtime; confirm nvidia-container-runtime is on PATH and restart k3s"

# k3s regenerates the containerd configuration on every start, so the default
# runtime is set through k3s's own config drop-in instead of editing containerd
# files directly. The NVIDIA runtime is made the default rather than an opt-in
# RuntimeClass because the offload spec has no runtimeClassName field, so
# generated server Deployments cannot select a runtime handler themselves.
sudo mkdir -p "$k3s_dropin_dir"
sudo tee "$k3s_dropin" > /dev/null << 'EOF'
# Generated by configure-k3s-nvidia.sh
default-runtime: nvidia
EOF

info "Restarting k3s to apply the default runtime"
sudo systemctl restart k3s
kubectl --context "$context" wait --for=condition=Ready node --all --timeout=180s

sudo grep -q "default_runtime_name = 'nvidia'" "$generated_config" \
  || sudo grep -q 'default_runtime_name = "nvidia"' "$generated_config" \
  || fatal "k3s did not apply the NVIDIA default runtime; inspect $generated_config"
info "Containerd default runtime is nvidia"

#------------------------------------------------------------------------------
# Install the NVIDIA Device Plugin
#------------------------------------------------------------------------------
section "Installing the NVIDIA Device Plugin"

kubectl --context "$context" apply -f - << EOF
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:$DEVICE_PLUGIN_VERSION
          env:
            - name: FAIL_ON_INIT_ERROR
              value: "true"
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
EOF

# A device plugin pod created before the runtime change keeps its original
# sandbox across CrashLoopBackOff restarts, so it never picks up the nvidia
# runtime and fails with "invalid device discovery strategy". Delete any
# existing pods so they are recreated under the configured default runtime.
kubectl --context "$context" delete pod \
  --namespace kube-system \
  --selector name=nvidia-device-plugin-ds \
  --ignore-not-found

kubectl --context "$context" rollout status daemonset/nvidia-device-plugin-daemonset \
  --namespace kube-system \
  --timeout="${register_timeout}s"

#------------------------------------------------------------------------------
# Wait for GPU Registration
#------------------------------------------------------------------------------
section "Waiting for nvidia.com/gpu"

# The rollout completes when the pod is Running, but kubelet publishes the
# resource only after the plugin registers over its gRPC socket.
node="$(kubectl --context "$context" get nodes -o jsonpath='{.items[0].metadata.name}')"
interval=5
elapsed=0
while :; do
  gpu_allocatable="$(kubectl --context "$context" get node "$node" \
    -o jsonpath='{.status.allocatable.nvidia\.com/gpu}' 2> /dev/null || true)"
  if [[ -n "$gpu_allocatable" && "$gpu_allocatable" != "0" ]]; then
    break
  fi
  if [[ "$elapsed" -ge "$register_timeout" ]]; then
    kubectl --context "$context" logs --namespace kube-system \
      --selector name=nvidia-device-plugin-ds --tail=50 >&2 || true
    fatal "Timed out after ${register_timeout}s waiting for nvidia.com/gpu; raise GPU_PLUGIN_REGISTER_TIMEOUT"
  fi
  info "Waiting for the device plugin to register nvidia.com/gpu (${elapsed}s/${register_timeout}s)"
  sleep "$interval"
  elapsed=$((elapsed + interval))
done

#------------------------------------------------------------------------------
# Summary
#------------------------------------------------------------------------------
section "Deployment Summary"
print_kv "Kube context" "$context"
print_kv "Node" "$node"
print_kv "Allocatable nvidia.com/gpu" "$gpu_allocatable"
print_kv "Device plugin" "$DEVICE_PLUGIN_VERSION"
info "Bare-metal GPU is available to Kubernetes workloads"
